/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.api;

import com.kanmon.client.ApiException;
import com.kanmon.client.model.BadRequestException;
import java.math.BigDecimal;
import com.kanmon.client.model.DrawRequest;
import com.kanmon.client.model.DrawRequestNotFoundException;
import com.kanmon.client.model.ForbiddenException;
import com.kanmon.client.model.GetDrawRequestsResponse;
import com.kanmon.client.model.InternalServerErrorException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DrawRequestsApi
 */
@Disabled
public class DrawRequestsApiTest {

    private final DrawRequestsApi api = new DrawRequestsApi();

    /**
     * Fetch draw requests
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllDrawRequestsTest() throws ApiException {
        String statuses = null;
        String ids = null;
        String platformBusinessIds = null;
        String businessIds = null;
        BigDecimal offset = null;
        BigDecimal limit = null;
        String createdAtStart = null;
        String createdAtEnd = null;
        GetDrawRequestsResponse response = api.getAllDrawRequests(statuses, ids, platformBusinessIds, businessIds, offset, limit, createdAtStart, createdAtEnd);
        // TODO: test validations
    }

    /**
     * Fetch a draw request
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDrawRequestTest() throws ApiException {
        String id = null;
        DrawRequest response = api.getDrawRequest(id);
        // TODO: test validations
    }

}
