/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.api;

import com.kanmon.client.ApiException;
import com.kanmon.client.model.BadRequestException;
import com.kanmon.client.model.Business;
import com.kanmon.client.model.ForbiddenException;
import com.kanmon.client.model.InternalServerErrorException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SandboxUtilitiesApi
 */
@Disabled
public class SandboxUtilitiesApiTest {

    private final SandboxUtilitiesApi api = new SandboxUtilitiesApi();

    /**
     * Delete a business in sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sandboxDeleteBusinessTest() throws ApiException {
        Object id = null;
        api.sandboxDeleteBusiness(id);
        // TODO: test validations
    }

    /**
     * Reset a business in sandbox
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sandboxResetBusinessTest() throws ApiException {
        Object id = null;
        Business response = api.sandboxResetBusiness(id);
        // TODO: test validations
    }

}
