/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms.  ## Rate limiting  Endpoints in this API enforce a per-platform request quota. Responses include the following headers when a quota is in effect:  - `X-RateLimit-Limit` — maximum requests allowed per minute. - `X-RateLimit-Remaining` — requests remaining in the current window.  When the quota is exhausted the API responds with `429 Too Many Requests`. Platforms without a configured quota are unlimited and these headers are omitted.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessDocument } from './BusinessDocument';
import {
    BusinessDocumentFromJSON,
    BusinessDocumentFromJSONTyped,
    BusinessDocumentToJSON,
} from './BusinessDocument';

/**
 * 
 * @export
 * @interface CreateBusinessDocumentsResponse
 */
export interface CreateBusinessDocumentsResponse {
    /**
     * The documents that were uploaded.
     * @type {Array<BusinessDocument>}
     * @memberof CreateBusinessDocumentsResponse
     */
    documents: Array<BusinessDocument>;
}

/**
 * Check if a given object implements the CreateBusinessDocumentsResponse interface.
 */
export function instanceOfCreateBusinessDocumentsResponse(value: object): value is CreateBusinessDocumentsResponse {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function CreateBusinessDocumentsResponseFromJSON(json: any): CreateBusinessDocumentsResponse {
    return CreateBusinessDocumentsResponseFromJSONTyped(json, false);
}

export function CreateBusinessDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBusinessDocumentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(BusinessDocumentFromJSON)),
    };
}

export function CreateBusinessDocumentsResponseToJSON(value?: CreateBusinessDocumentsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'documents': ((value['documents'] as Array<any>).map(BusinessDocumentToJSON)),
    };
}

