/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BusinessHasNoInvoiceFinancingProductException } from './BusinessHasNoInvoiceFinancingProductException';
import {
    instanceOfBusinessHasNoInvoiceFinancingProductException,
    BusinessHasNoInvoiceFinancingProductExceptionFromJSON,
    BusinessHasNoInvoiceFinancingProductExceptionFromJSONTyped,
    BusinessHasNoInvoiceFinancingProductExceptionToJSON,
} from './BusinessHasNoInvoiceFinancingProductException';
import type { PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException } from './PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException';
import {
    instanceOfPlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException,
    PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductExceptionFromJSON,
    PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductExceptionFromJSONTyped,
    PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductExceptionToJSON,
} from './PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException';

/**
 * @type CreateEmbeddedSession409Response
 * 
 * @export
 */
export type CreateEmbeddedSession409Response = BusinessHasNoInvoiceFinancingProductException | PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException;

export function CreateEmbeddedSession409ResponseFromJSON(json: any): CreateEmbeddedSession409Response {
    return CreateEmbeddedSession409ResponseFromJSONTyped(json, false);
}

export function CreateEmbeddedSession409ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmbeddedSession409Response {
    if (json == null) {
        return json;
    }
    return BusinessHasNoInvoiceFinancingProductExceptionFromJSONTyped(json, true) || PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductExceptionFromJSONTyped(json, true);
}

export function CreateEmbeddedSession409ResponseToJSON(value?: CreateEmbeddedSession409Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBusinessHasNoInvoiceFinancingProductException(value)) {
        return BusinessHasNoInvoiceFinancingProductExceptionToJSON(value as BusinessHasNoInvoiceFinancingProductException);
    }
    if (instanceOfPlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException(value)) {
        return PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductExceptionToJSON(value as PlatformInvoiceIdAlreadyExistsForAnotherIssuedProductException);
    }

    return {};
}

