/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DrawRequestState = {
    DrawRequestCreated: 'DRAW_REQUEST_CREATED',
    DrawRequestFunded: 'DRAW_REQUEST_FUNDED',
    DrawRequestPaidInFull: 'DRAW_REQUEST_PAID_IN_FULL',
    Rejected: 'REJECTED',
    Defaulted: 'DEFAULTED'
} as const;
export type DrawRequestState = typeof DrawRequestState[keyof typeof DrawRequestState];


export function instanceOfDrawRequestState(value: any): boolean {
    return Object.values(DrawRequestState).includes(value);
}

export function DrawRequestStateFromJSON(json: any): DrawRequestState {
    return DrawRequestStateFromJSONTyped(json, false);
}

export function DrawRequestStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrawRequestState {
    return json as DrawRequestState;
}

export function DrawRequestStateToJSON(value?: DrawRequestState | null): any {
    return value as any;
}

