/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForbiddenException
 */
export interface ForbiddenException {
    /**
     * Safe for programmatic use.
     * @type {string}
     * @memberof ForbiddenException
     */
    errorCode: ForbiddenExceptionErrorCodeEnum;
    /**
     * The human readable description of the error.
     * @type {string}
     * @memberof ForbiddenException
     */
    message: string;
    /**
     * When the error occurred - ISO 8601 format.
     * @type {string}
     * @memberof ForbiddenException
     */
    timestamp: string;
}


/**
 * @export
 */
export const ForbiddenExceptionErrorCodeEnum = {
    ForbiddenException: 'ForbiddenException'
} as const;
export type ForbiddenExceptionErrorCodeEnum = typeof ForbiddenExceptionErrorCodeEnum[keyof typeof ForbiddenExceptionErrorCodeEnum];


/**
 * Check if a given object implements the ForbiddenException interface.
 */
export function instanceOfForbiddenException(value: object): value is ForbiddenException {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ForbiddenExceptionFromJSON(json: any): ForbiddenException {
    return ForbiddenExceptionFromJSONTyped(json, false);
}

export function ForbiddenExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenException {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function ForbiddenExceptionToJSON(value?: ForbiddenException | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errorCode': value['errorCode'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

