/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentIntent } from './PaymentIntent';
import {
    PaymentIntentFromJSON,
    PaymentIntentFromJSONTyped,
    PaymentIntentToJSON,
} from './PaymentIntent';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface GetPaymentIntentsResponse
 */
export interface GetPaymentIntentsResponse {
    /**
     * Array of payment intents.
     * @type {Array<PaymentIntent>}
     * @memberof GetPaymentIntentsResponse
     */
    paymentIntents: Array<PaymentIntent>;
    /**
     * Pagination metadata.
     * @type {PaginationResult}
     * @memberof GetPaymentIntentsResponse
     */
    pagination: PaginationResult;
}

/**
 * Check if a given object implements the GetPaymentIntentsResponse interface.
 */
export function instanceOfGetPaymentIntentsResponse(value: object): value is GetPaymentIntentsResponse {
    if (!('paymentIntents' in value) || value['paymentIntents'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function GetPaymentIntentsResponseFromJSON(json: any): GetPaymentIntentsResponse {
    return GetPaymentIntentsResponseFromJSONTyped(json, false);
}

export function GetPaymentIntentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaymentIntentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntents': ((json['paymentIntents'] as Array<any>).map(PaymentIntentFromJSON)),
        'pagination': PaginationResultFromJSON(json['pagination']),
    };
}

export function GetPaymentIntentsResponseToJSON(value?: GetPaymentIntentsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'paymentIntents': ((value['paymentIntents'] as Array<any>).map(PaymentIntentToJSON)),
        'pagination': PaginationResultToJSON(value['pagination']),
    };
}

