/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionInvoiceWithInvoiceFile } from './SessionInvoiceWithInvoiceFile';
import {
    SessionInvoiceWithInvoiceFileFromJSON,
    SessionInvoiceWithInvoiceFileFromJSONTyped,
    SessionInvoiceWithInvoiceFileToJSON,
} from './SessionInvoiceWithInvoiceFile';

/**
 * 
 * @export
 * @interface InvoiceFlowWithInvoiceFileSessionTokenData
 */
export interface InvoiceFlowWithInvoiceFileSessionTokenData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceFlowWithInvoiceFileSessionTokenData
     */
    component: InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum;
    /**
     * Details about the list of invoices which are to be created.
     * @type {Array<SessionInvoiceWithInvoiceFile>}
     * @memberof InvoiceFlowWithInvoiceFileSessionTokenData
     */
    invoices: Array<SessionInvoiceWithInvoiceFile>;
}


/**
 * @export
 */
export const InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum = {
    SessionInvoiceFlowWithInvoiceFile: 'SESSION_INVOICE_FLOW_WITH_INVOICE_FILE'
} as const;
export type InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum = typeof InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum[keyof typeof InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum];


/**
 * Check if a given object implements the InvoiceFlowWithInvoiceFileSessionTokenData interface.
 */
export function instanceOfInvoiceFlowWithInvoiceFileSessionTokenData(value: object): boolean {
    if (!('component' in value)) return false;
    if (!('invoices' in value)) return false;
    return true;
}

export function InvoiceFlowWithInvoiceFileSessionTokenDataFromJSON(json: any): InvoiceFlowWithInvoiceFileSessionTokenData {
    return InvoiceFlowWithInvoiceFileSessionTokenDataFromJSONTyped(json, false);
}

export function InvoiceFlowWithInvoiceFileSessionTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceFlowWithInvoiceFileSessionTokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'component': json['component'],
        'invoices': ((json['invoices'] as Array<any>).map(SessionInvoiceWithInvoiceFileFromJSON)),
    };
}

export function InvoiceFlowWithInvoiceFileSessionTokenDataToJSON(value?: InvoiceFlowWithInvoiceFileSessionTokenData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'component': value['component'],
        'invoices': ((value['invoices'] as Array<any>).map(SessionInvoiceWithInvoiceFileToJSON)),
    };
}

