/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceNotFoundException
 */
export interface InvoiceNotFoundException {
    /**
     * Safe for programmatic use.
     * @type {string}
     * @memberof InvoiceNotFoundException
     */
    errorCode: InvoiceNotFoundExceptionErrorCodeEnum;
    /**
     * The human readable description of the error.
     * @type {string}
     * @memberof InvoiceNotFoundException
     */
    message: string;
    /**
     * When the error occurred - ISO 8601 format.
     * @type {string}
     * @memberof InvoiceNotFoundException
     */
    timestamp: string;
}


/**
 * @export
 */
export const InvoiceNotFoundExceptionErrorCodeEnum = {
    InvoiceNotFoundException: 'InvoiceNotFoundException'
} as const;
export type InvoiceNotFoundExceptionErrorCodeEnum = typeof InvoiceNotFoundExceptionErrorCodeEnum[keyof typeof InvoiceNotFoundExceptionErrorCodeEnum];


/**
 * Check if a given object implements the InvoiceNotFoundException interface.
 */
export function instanceOfInvoiceNotFoundException(value: object): boolean {
    if (!('errorCode' in value)) return false;
    if (!('message' in value)) return false;
    if (!('timestamp' in value)) return false;
    return true;
}

export function InvoiceNotFoundExceptionFromJSON(json: any): InvoiceNotFoundException {
    return InvoiceNotFoundExceptionFromJSONTyped(json, false);
}

export function InvoiceNotFoundExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceNotFoundException {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function InvoiceNotFoundExceptionToJSON(value?: InvoiceNotFoundException | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errorCode': value['errorCode'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

