/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InvoiceFinancingServicingData } from './InvoiceFinancingServicingData';
import {
    instanceOfInvoiceFinancingServicingData,
    InvoiceFinancingServicingDataFromJSON,
    InvoiceFinancingServicingDataFromJSONTyped,
    InvoiceFinancingServicingDataToJSON,
} from './InvoiceFinancingServicingData';
import type { LineOfCreditServicingData } from './LineOfCreditServicingData';
import {
    instanceOfLineOfCreditServicingData,
    LineOfCreditServicingDataFromJSON,
    LineOfCreditServicingDataFromJSONTyped,
    LineOfCreditServicingDataToJSON,
} from './LineOfCreditServicingData';
import type { McaServicingData } from './McaServicingData';
import {
    instanceOfMcaServicingData,
    McaServicingDataFromJSON,
    McaServicingDataFromJSONTyped,
    McaServicingDataToJSON,
} from './McaServicingData';
import type { TermLoanServicingData } from './TermLoanServicingData';
import {
    instanceOfTermLoanServicingData,
    TermLoanServicingDataFromJSON,
    TermLoanServicingDataFromJSONTyped,
    TermLoanServicingDataToJSON,
} from './TermLoanServicingData';

/**
 * @type IssuedProductServicingData
 * The data needed to service this specific type of issued product
 * @export
 */
export type IssuedProductServicingData = { productType: 'InvoiceFinancingServicingData' } & InvoiceFinancingServicingData | { productType: 'LineOfCreditServicingData' } & LineOfCreditServicingData | { productType: 'McaServicingData' } & McaServicingData | { productType: 'TermLoanServicingData' } & TermLoanServicingData;

export function IssuedProductServicingDataFromJSON(json: any): IssuedProductServicingData {
    return IssuedProductServicingDataFromJSONTyped(json, false);
}

export function IssuedProductServicingDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuedProductServicingData {
    if (json == null) {
        return json;
    }
    switch (json['productType']) {
        case 'InvoiceFinancingServicingData':
            return Object.assign({}, InvoiceFinancingServicingDataFromJSONTyped(json, true), { productType: 'InvoiceFinancingServicingData' } as const);
        case 'LineOfCreditServicingData':
            return Object.assign({}, LineOfCreditServicingDataFromJSONTyped(json, true), { productType: 'LineOfCreditServicingData' } as const);
        case 'McaServicingData':
            return Object.assign({}, McaServicingDataFromJSONTyped(json, true), { productType: 'McaServicingData' } as const);
        case 'TermLoanServicingData':
            return Object.assign({}, TermLoanServicingDataFromJSONTyped(json, true), { productType: 'TermLoanServicingData' } as const);
        default:
            throw new Error(`No variant of IssuedProductServicingData exists with 'productType=${json['productType']}'`);
    }
}

export function IssuedProductServicingDataToJSON(value?: IssuedProductServicingData | null): any {
    if (value == null) {
        return value;
    }
    switch (value['productType']) {
        case 'InvoiceFinancingServicingData':
            return InvoiceFinancingServicingDataToJSON(value);
        case 'LineOfCreditServicingData':
            return LineOfCreditServicingDataToJSON(value);
        case 'McaServicingData':
            return McaServicingDataToJSON(value);
        case 'TermLoanServicingData':
            return TermLoanServicingDataToJSON(value);
        default:
            throw new Error(`No variant of IssuedProductServicingData exists with 'productType=${value['productType']}'`);
    }

}

