/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms.  ## Rate limiting  Endpoints in this API enforce a per-platform request quota. Responses include the following headers when a quota is in effect:  - `X-RateLimit-Limit` — maximum requests allowed per minute. - `X-RateLimit-Remaining` — requests remaining in the current window.  When the quota is exhausted the API responds with `429 Too Many Requests`. Platforms without a configured quota are unlimited and these headers are omitted.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface MergeUsersResponseBody
 */
export interface MergeUsersResponseBody {
    /**
     * An array of users that were merged into the target business.
     * @type {Array<User>}
     * @memberof MergeUsersResponseBody
     */
    mergedUsers: Array<User>;
}

/**
 * Check if a given object implements the MergeUsersResponseBody interface.
 */
export function instanceOfMergeUsersResponseBody(value: object): value is MergeUsersResponseBody {
    if (!('mergedUsers' in value) || value['mergedUsers'] === undefined) return false;
    return true;
}

export function MergeUsersResponseBodyFromJSON(json: any): MergeUsersResponseBody {
    return MergeUsersResponseBodyFromJSONTyped(json, false);
}

export function MergeUsersResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeUsersResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'mergedUsers': ((json['mergedUsers'] as Array<any>).map(UserFromJSON)),
    };
}

export function MergeUsersResponseBodyToJSON(value?: MergeUsersResponseBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mergedUsers': ((value['mergedUsers'] as Array<any>).map(UserToJSON)),
    };
}

