/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms.  ## Rate limiting  Endpoints in this API enforce a per-platform request quota. Responses include the following headers when a quota is in effect:  - `X-RateLimit-Limit` — maximum requests allowed per minute. - `X-RateLimit-Remaining` — requests remaining in the current window.  When the quota is exhausted the API responds with `429 Too Many Requests`. Platforms without a configured quota are unlimited and these headers are omitted.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the payment.
 * @export
 */
export const PaymentOrderStatus = {
    FAILED: 'FAILED',
    PAID: 'PAID',
    PENDING: 'PENDING'
} as const;
export type PaymentOrderStatus = typeof PaymentOrderStatus[keyof typeof PaymentOrderStatus];


export function instanceOfPaymentOrderStatus(value: any): boolean {
    for (const key in PaymentOrderStatus) {
        if (Object.prototype.hasOwnProperty.call(PaymentOrderStatus, key)) {
            if (PaymentOrderStatus[key as keyof typeof PaymentOrderStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentOrderStatusFromJSON(json: any): PaymentOrderStatus {
    return PaymentOrderStatusFromJSONTyped(json, false);
}

export function PaymentOrderStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentOrderStatus {
    return json as PaymentOrderStatus;
}

export function PaymentOrderStatusToJSON(value?: PaymentOrderStatus | null): any {
    return value as any;
}

