/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrimaryBusinessOwnerAlreadyExistsForBusinessException
 */
export interface PrimaryBusinessOwnerAlreadyExistsForBusinessException {
    /**
     * Safe for programmatic use.
     * @type {string}
     * @memberof PrimaryBusinessOwnerAlreadyExistsForBusinessException
     */
    errorCode: PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionErrorCodeEnum;
    /**
     * The human readable description of the error.
     * @type {string}
     * @memberof PrimaryBusinessOwnerAlreadyExistsForBusinessException
     */
    message: string;
    /**
     * When the error occurred - ISO 8601 format.
     * @type {string}
     * @memberof PrimaryBusinessOwnerAlreadyExistsForBusinessException
     */
    timestamp: string;
}


/**
 * @export
 */
export const PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionErrorCodeEnum = {
    PrimaryBusinessOwnerAlreadyExistsForBusinessException: 'PrimaryBusinessOwnerAlreadyExistsForBusinessException'
} as const;
export type PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionErrorCodeEnum = typeof PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionErrorCodeEnum[keyof typeof PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionErrorCodeEnum];


/**
 * Check if a given object implements the PrimaryBusinessOwnerAlreadyExistsForBusinessException interface.
 */
export function instanceOfPrimaryBusinessOwnerAlreadyExistsForBusinessException(value: object): value is PrimaryBusinessOwnerAlreadyExistsForBusinessException {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionFromJSON(json: any): PrimaryBusinessOwnerAlreadyExistsForBusinessException {
    return PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionFromJSONTyped(json, false);
}

export function PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrimaryBusinessOwnerAlreadyExistsForBusinessException {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function PrimaryBusinessOwnerAlreadyExistsForBusinessExceptionToJSON(value?: PrimaryBusinessOwnerAlreadyExistsForBusinessException | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errorCode': value['errorCode'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

