/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms.  ## Rate limiting  Endpoints in this API enforce a per-platform request quota. Responses include the following headers when a quota is in effect:  - `X-RateLimit-Limit` — maximum requests allowed per minute. - `X-RateLimit-Remaining` — requests remaining in the current window.  When the quota is exhausted the API responds with `429 Too Many Requests`. Platforms without a configured quota are unlimited and these headers are omitted.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RepaymentCadence = {
    WEEKLY: 'WEEKLY',
    MONTHLY: 'MONTHLY'
} as const;
export type RepaymentCadence = typeof RepaymentCadence[keyof typeof RepaymentCadence];


export function instanceOfRepaymentCadence(value: any): boolean {
    for (const key in RepaymentCadence) {
        if (Object.prototype.hasOwnProperty.call(RepaymentCadence, key)) {
            if (RepaymentCadence[key as keyof typeof RepaymentCadence] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RepaymentCadenceFromJSON(json: any): RepaymentCadence {
    return RepaymentCadenceFromJSONTyped(json, false);
}

export function RepaymentCadenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepaymentCadence {
    return json as RepaymentCadence;
}

export function RepaymentCadenceToJSON(value?: RepaymentCadence | null): any {
    return value as any;
}

