/* tslint:disable */
/* eslint-disable */
/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserNotFoundException
 */
export interface UserNotFoundException {
    /**
     * Safe for programmatic use.
     * @type {string}
     * @memberof UserNotFoundException
     */
    errorCode: UserNotFoundExceptionErrorCodeEnum;
    /**
     * The human readable description of the error.
     * @type {string}
     * @memberof UserNotFoundException
     */
    message: string;
    /**
     * When the error occurred - ISO 8601 format.
     * @type {string}
     * @memberof UserNotFoundException
     */
    timestamp: string;
}


/**
 * @export
 */
export const UserNotFoundExceptionErrorCodeEnum = {
    UserNotFoundException: 'UserNotFoundException'
} as const;
export type UserNotFoundExceptionErrorCodeEnum = typeof UserNotFoundExceptionErrorCodeEnum[keyof typeof UserNotFoundExceptionErrorCodeEnum];


/**
 * Check if a given object implements the UserNotFoundException interface.
 */
export function instanceOfUserNotFoundException(value: object): value is UserNotFoundException {
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function UserNotFoundExceptionFromJSON(json: any): UserNotFoundException {
    return UserNotFoundExceptionFromJSONTyped(json, false);
}

export function UserNotFoundExceptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNotFoundException {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function UserNotFoundExceptionToJSON(value?: UserNotFoundException | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'errorCode': value['errorCode'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

