/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.kanmon.client.JSON;

/**
 * CreateIntegratedMcaReceivableBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class CreateIntegratedMcaReceivableBody {
  public static final String SERIALIZED_NAME_ISSUED_PRODUCT_ID = "issuedProductId";
  @SerializedName(SERIALIZED_NAME_ISSUED_PRODUCT_ID)
  private String issuedProductId;

  public static final String SERIALIZED_NAME_CHARGE_AMOUNT_CENTS = "chargeAmountCents";
  @SerializedName(SERIALIZED_NAME_CHARGE_AMOUNT_CENTS)
  private BigDecimal chargeAmountCents;

  public static final String SERIALIZED_NAME_REPAYMENT_AMOUNT_CENTS = "repaymentAmountCents";
  @SerializedName(SERIALIZED_NAME_REPAYMENT_AMOUNT_CENTS)
  private BigDecimal repaymentAmountCents;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_TRANSACTION_TIME = "transactionTime";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TIME)
  private String transactionTime;

  public CreateIntegratedMcaReceivableBody() {
  }

  public CreateIntegratedMcaReceivableBody issuedProductId(String issuedProductId) {
    this.issuedProductId = issuedProductId;
    return this;
  }

  /**
   * The unique identifier for the issued product in Kanmon′s system.
   * @return issuedProductId
   */
  @javax.annotation.Nonnull
  public String getIssuedProductId() {
    return issuedProductId;
  }

  public void setIssuedProductId(String issuedProductId) {
    this.issuedProductId = issuedProductId;
  }


  public CreateIntegratedMcaReceivableBody chargeAmountCents(BigDecimal chargeAmountCents) {
    this.chargeAmountCents = chargeAmountCents;
    return this;
  }

  /**
   * The charge amount - in cents.
   * @return chargeAmountCents
   */
  @javax.annotation.Nonnull
  public BigDecimal getChargeAmountCents() {
    return chargeAmountCents;
  }

  public void setChargeAmountCents(BigDecimal chargeAmountCents) {
    this.chargeAmountCents = chargeAmountCents;
  }


  public CreateIntegratedMcaReceivableBody repaymentAmountCents(BigDecimal repaymentAmountCents) {
    this.repaymentAmountCents = repaymentAmountCents;
    return this;
  }

  /**
   *    &lt;p&gt;The repayment amount - in cents. It should be the lesser of:     &lt;br/&gt;     ( repayment percentage &amp;times; charge amount ) or remaining balance   &lt;/p&gt; 
   * @return repaymentAmountCents
   */
  @javax.annotation.Nonnull
  public BigDecimal getRepaymentAmountCents() {
    return repaymentAmountCents;
  }

  public void setRepaymentAmountCents(BigDecimal repaymentAmountCents) {
    this.repaymentAmountCents = repaymentAmountCents;
  }


  public CreateIntegratedMcaReceivableBody transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Your platform’s unique ID for the transaction.
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public CreateIntegratedMcaReceivableBody transactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
    return this;
  }

  /**
   * Creation UTC ISO 8601 timestamp of the transaction.
   * @return transactionTime
   */
  @javax.annotation.Nonnull
  public String getTransactionTime() {
    return transactionTime;
  }

  public void setTransactionTime(String transactionTime) {
    this.transactionTime = transactionTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateIntegratedMcaReceivableBody createIntegratedMcaReceivableBody = (CreateIntegratedMcaReceivableBody) o;
    return Objects.equals(this.issuedProductId, createIntegratedMcaReceivableBody.issuedProductId) &&
        Objects.equals(this.chargeAmountCents, createIntegratedMcaReceivableBody.chargeAmountCents) &&
        Objects.equals(this.repaymentAmountCents, createIntegratedMcaReceivableBody.repaymentAmountCents) &&
        Objects.equals(this.transactionId, createIntegratedMcaReceivableBody.transactionId) &&
        Objects.equals(this.transactionTime, createIntegratedMcaReceivableBody.transactionTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedProductId, chargeAmountCents, repaymentAmountCents, transactionId, transactionTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateIntegratedMcaReceivableBody {\n");
    sb.append("    issuedProductId: ").append(toIndentedString(issuedProductId)).append("\n");
    sb.append("    chargeAmountCents: ").append(toIndentedString(chargeAmountCents)).append("\n");
    sb.append("    repaymentAmountCents: ").append(toIndentedString(repaymentAmountCents)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transactionTime: ").append(toIndentedString(transactionTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("issuedProductId");
    openapiFields.add("chargeAmountCents");
    openapiFields.add("repaymentAmountCents");
    openapiFields.add("transactionId");
    openapiFields.add("transactionTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("issuedProductId");
    openapiRequiredFields.add("chargeAmountCents");
    openapiRequiredFields.add("repaymentAmountCents");
    openapiRequiredFields.add("transactionId");
    openapiRequiredFields.add("transactionTime");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateIntegratedMcaReceivableBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateIntegratedMcaReceivableBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateIntegratedMcaReceivableBody is not found in the empty JSON string", CreateIntegratedMcaReceivableBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateIntegratedMcaReceivableBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateIntegratedMcaReceivableBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateIntegratedMcaReceivableBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("issuedProductId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issuedProductId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issuedProductId").toString()));
      }
      if (!jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if (!jsonObj.get("transactionTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionTime").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateIntegratedMcaReceivableBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateIntegratedMcaReceivableBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateIntegratedMcaReceivableBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateIntegratedMcaReceivableBody.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateIntegratedMcaReceivableBody>() {
           @Override
           public void write(JsonWriter out, CreateIntegratedMcaReceivableBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateIntegratedMcaReceivableBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateIntegratedMcaReceivableBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateIntegratedMcaReceivableBody
   * @throws IOException if the JSON string is invalid with respect to CreateIntegratedMcaReceivableBody
   */
  public static CreateIntegratedMcaReceivableBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateIntegratedMcaReceivableBody.class);
  }

  /**
   * Convert an instance of CreateIntegratedMcaReceivableBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

