/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kanmon.client.model.IncorrectProductTypeException;
import com.kanmon.client.model.InsufficientCreditLimitException;
import com.kanmon.client.model.IssuedProductStatusNotCurrentException;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.kanmon.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class FinanceInvoice409Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(FinanceInvoice409Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!FinanceInvoice409Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'FinanceInvoice409Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<IssuedProductStatusNotCurrentException> adapterIssuedProductStatusNotCurrentException = gson.getDelegateAdapter(this, TypeToken.get(IssuedProductStatusNotCurrentException.class));
            final TypeAdapter<IncorrectProductTypeException> adapterIncorrectProductTypeException = gson.getDelegateAdapter(this, TypeToken.get(IncorrectProductTypeException.class));
            final TypeAdapter<InsufficientCreditLimitException> adapterInsufficientCreditLimitException = gson.getDelegateAdapter(this, TypeToken.get(InsufficientCreditLimitException.class));

            return (TypeAdapter<T>) new TypeAdapter<FinanceInvoice409Response>() {
                @Override
                public void write(JsonWriter out, FinanceInvoice409Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `IssuedProductStatusNotCurrentException`
                    if (value.getActualInstance() instanceof IssuedProductStatusNotCurrentException) {
                        JsonElement element = adapterIssuedProductStatusNotCurrentException.toJsonTree((IssuedProductStatusNotCurrentException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `IncorrectProductTypeException`
                    if (value.getActualInstance() instanceof IncorrectProductTypeException) {
                        JsonElement element = adapterIncorrectProductTypeException.toJsonTree((IncorrectProductTypeException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `InsufficientCreditLimitException`
                    if (value.getActualInstance() instanceof InsufficientCreditLimitException) {
                        JsonElement element = adapterInsufficientCreditLimitException.toJsonTree((InsufficientCreditLimitException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: IncorrectProductTypeException, InsufficientCreditLimitException, IssuedProductStatusNotCurrentException");
                }

                @Override
                public FinanceInvoice409Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize IssuedProductStatusNotCurrentException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        IssuedProductStatusNotCurrentException.validateJsonElement(jsonElement);
                        actualAdapter = adapterIssuedProductStatusNotCurrentException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'IssuedProductStatusNotCurrentException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for IssuedProductStatusNotCurrentException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'IssuedProductStatusNotCurrentException'", e);
                    }
                    // deserialize IncorrectProductTypeException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        IncorrectProductTypeException.validateJsonElement(jsonElement);
                        actualAdapter = adapterIncorrectProductTypeException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'IncorrectProductTypeException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for IncorrectProductTypeException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'IncorrectProductTypeException'", e);
                    }
                    // deserialize InsufficientCreditLimitException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        InsufficientCreditLimitException.validateJsonElement(jsonElement);
                        actualAdapter = adapterInsufficientCreditLimitException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'InsufficientCreditLimitException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for InsufficientCreditLimitException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'InsufficientCreditLimitException'", e);
                    }

                    if (match == 1) {
                        FinanceInvoice409Response ret = new FinanceInvoice409Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for FinanceInvoice409Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public FinanceInvoice409Response() {
        super("oneOf", Boolean.FALSE);
    }

    public FinanceInvoice409Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("IssuedProductStatusNotCurrentException", IssuedProductStatusNotCurrentException.class);
        schemas.put("IncorrectProductTypeException", IncorrectProductTypeException.class);
        schemas.put("InsufficientCreditLimitException", InsufficientCreditLimitException.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return FinanceInvoice409Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * IncorrectProductTypeException, InsufficientCreditLimitException, IssuedProductStatusNotCurrentException
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof IssuedProductStatusNotCurrentException) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof IncorrectProductTypeException) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof InsufficientCreditLimitException) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be IncorrectProductTypeException, InsufficientCreditLimitException, IssuedProductStatusNotCurrentException");
    }

    /**
     * Get the actual instance, which can be the following:
     * IncorrectProductTypeException, InsufficientCreditLimitException, IssuedProductStatusNotCurrentException
     *
     * @return The actual instance (IncorrectProductTypeException, InsufficientCreditLimitException, IssuedProductStatusNotCurrentException)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `IssuedProductStatusNotCurrentException`. If the actual instance is not `IssuedProductStatusNotCurrentException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IssuedProductStatusNotCurrentException`
     * @throws ClassCastException if the instance is not `IssuedProductStatusNotCurrentException`
     */
    public IssuedProductStatusNotCurrentException getIssuedProductStatusNotCurrentException() throws ClassCastException {
        return (IssuedProductStatusNotCurrentException)super.getActualInstance();
    }
    /**
     * Get the actual instance of `IncorrectProductTypeException`. If the actual instance is not `IncorrectProductTypeException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IncorrectProductTypeException`
     * @throws ClassCastException if the instance is not `IncorrectProductTypeException`
     */
    public IncorrectProductTypeException getIncorrectProductTypeException() throws ClassCastException {
        return (IncorrectProductTypeException)super.getActualInstance();
    }
    /**
     * Get the actual instance of `InsufficientCreditLimitException`. If the actual instance is not `InsufficientCreditLimitException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `InsufficientCreditLimitException`
     * @throws ClassCastException if the instance is not `InsufficientCreditLimitException`
     */
    public InsufficientCreditLimitException getInsufficientCreditLimitException() throws ClassCastException {
        return (InsufficientCreditLimitException)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to FinanceInvoice409Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with IssuedProductStatusNotCurrentException
        try {
            IssuedProductStatusNotCurrentException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for IssuedProductStatusNotCurrentException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with IncorrectProductTypeException
        try {
            IncorrectProductTypeException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for IncorrectProductTypeException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with InsufficientCreditLimitException
        try {
            InsufficientCreditLimitException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for InsufficientCreditLimitException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for FinanceInvoice409Response with oneOf schemas: IncorrectProductTypeException, InsufficientCreditLimitException, IssuedProductStatusNotCurrentException. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of FinanceInvoice409Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of FinanceInvoice409Response
     * @throws IOException if the JSON string is invalid with respect to FinanceInvoice409Response
     */
    public static FinanceInvoice409Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, FinanceInvoice409Response.class);
    }

    /**
     * Convert an instance of FinanceInvoice409Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

