/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kanmon.client.model.IncorrectFinancingAmountException;
import com.kanmon.client.model.InvalidInvoiceDueDateException;
import com.kanmon.client.model.InvoicePaymentPlanNotFoundException;
import com.kanmon.client.model.PlatformInvoiceIdAlreadyExistsException;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.kanmon.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class FinanceInvoice400Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(FinanceInvoice400Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!FinanceInvoice400Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'FinanceInvoice400Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PlatformInvoiceIdAlreadyExistsException> adapterPlatformInvoiceIdAlreadyExistsException = gson.getDelegateAdapter(this, TypeToken.get(PlatformInvoiceIdAlreadyExistsException.class));
            final TypeAdapter<InvoicePaymentPlanNotFoundException> adapterInvoicePaymentPlanNotFoundException = gson.getDelegateAdapter(this, TypeToken.get(InvoicePaymentPlanNotFoundException.class));
            final TypeAdapter<InvalidInvoiceDueDateException> adapterInvalidInvoiceDueDateException = gson.getDelegateAdapter(this, TypeToken.get(InvalidInvoiceDueDateException.class));
            final TypeAdapter<IncorrectFinancingAmountException> adapterIncorrectFinancingAmountException = gson.getDelegateAdapter(this, TypeToken.get(IncorrectFinancingAmountException.class));

            return (TypeAdapter<T>) new TypeAdapter<FinanceInvoice400Response>() {
                @Override
                public void write(JsonWriter out, FinanceInvoice400Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `PlatformInvoiceIdAlreadyExistsException`
                    if (value.getActualInstance() instanceof PlatformInvoiceIdAlreadyExistsException) {
                        JsonElement element = adapterPlatformInvoiceIdAlreadyExistsException.toJsonTree((PlatformInvoiceIdAlreadyExistsException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `InvoicePaymentPlanNotFoundException`
                    if (value.getActualInstance() instanceof InvoicePaymentPlanNotFoundException) {
                        JsonElement element = adapterInvoicePaymentPlanNotFoundException.toJsonTree((InvoicePaymentPlanNotFoundException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `InvalidInvoiceDueDateException`
                    if (value.getActualInstance() instanceof InvalidInvoiceDueDateException) {
                        JsonElement element = adapterInvalidInvoiceDueDateException.toJsonTree((InvalidInvoiceDueDateException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `IncorrectFinancingAmountException`
                    if (value.getActualInstance() instanceof IncorrectFinancingAmountException) {
                        JsonElement element = adapterIncorrectFinancingAmountException.toJsonTree((IncorrectFinancingAmountException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: IncorrectFinancingAmountException, InvalidInvoiceDueDateException, InvoicePaymentPlanNotFoundException, PlatformInvoiceIdAlreadyExistsException");
                }

                @Override
                public FinanceInvoice400Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize PlatformInvoiceIdAlreadyExistsException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PlatformInvoiceIdAlreadyExistsException.validateJsonElement(jsonElement);
                        actualAdapter = adapterPlatformInvoiceIdAlreadyExistsException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'PlatformInvoiceIdAlreadyExistsException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for PlatformInvoiceIdAlreadyExistsException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'PlatformInvoiceIdAlreadyExistsException'", e);
                    }
                    // deserialize InvoicePaymentPlanNotFoundException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        InvoicePaymentPlanNotFoundException.validateJsonElement(jsonElement);
                        actualAdapter = adapterInvoicePaymentPlanNotFoundException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'InvoicePaymentPlanNotFoundException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for InvoicePaymentPlanNotFoundException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'InvoicePaymentPlanNotFoundException'", e);
                    }
                    // deserialize InvalidInvoiceDueDateException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        InvalidInvoiceDueDateException.validateJsonElement(jsonElement);
                        actualAdapter = adapterInvalidInvoiceDueDateException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'InvalidInvoiceDueDateException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for InvalidInvoiceDueDateException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'InvalidInvoiceDueDateException'", e);
                    }
                    // deserialize IncorrectFinancingAmountException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        IncorrectFinancingAmountException.validateJsonElement(jsonElement);
                        actualAdapter = adapterIncorrectFinancingAmountException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'IncorrectFinancingAmountException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for IncorrectFinancingAmountException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'IncorrectFinancingAmountException'", e);
                    }

                    if (match == 1) {
                        FinanceInvoice400Response ret = new FinanceInvoice400Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for FinanceInvoice400Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public FinanceInvoice400Response() {
        super("oneOf", Boolean.FALSE);
    }

    public FinanceInvoice400Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PlatformInvoiceIdAlreadyExistsException", PlatformInvoiceIdAlreadyExistsException.class);
        schemas.put("InvoicePaymentPlanNotFoundException", InvoicePaymentPlanNotFoundException.class);
        schemas.put("InvalidInvoiceDueDateException", InvalidInvoiceDueDateException.class);
        schemas.put("IncorrectFinancingAmountException", IncorrectFinancingAmountException.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return FinanceInvoice400Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * IncorrectFinancingAmountException, InvalidInvoiceDueDateException, InvoicePaymentPlanNotFoundException, PlatformInvoiceIdAlreadyExistsException
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof PlatformInvoiceIdAlreadyExistsException) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof InvoicePaymentPlanNotFoundException) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof InvalidInvoiceDueDateException) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof IncorrectFinancingAmountException) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be IncorrectFinancingAmountException, InvalidInvoiceDueDateException, InvoicePaymentPlanNotFoundException, PlatformInvoiceIdAlreadyExistsException");
    }

    /**
     * Get the actual instance, which can be the following:
     * IncorrectFinancingAmountException, InvalidInvoiceDueDateException, InvoicePaymentPlanNotFoundException, PlatformInvoiceIdAlreadyExistsException
     *
     * @return The actual instance (IncorrectFinancingAmountException, InvalidInvoiceDueDateException, InvoicePaymentPlanNotFoundException, PlatformInvoiceIdAlreadyExistsException)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PlatformInvoiceIdAlreadyExistsException`. If the actual instance is not `PlatformInvoiceIdAlreadyExistsException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PlatformInvoiceIdAlreadyExistsException`
     * @throws ClassCastException if the instance is not `PlatformInvoiceIdAlreadyExistsException`
     */
    public PlatformInvoiceIdAlreadyExistsException getPlatformInvoiceIdAlreadyExistsException() throws ClassCastException {
        return (PlatformInvoiceIdAlreadyExistsException)super.getActualInstance();
    }
    /**
     * Get the actual instance of `InvoicePaymentPlanNotFoundException`. If the actual instance is not `InvoicePaymentPlanNotFoundException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `InvoicePaymentPlanNotFoundException`
     * @throws ClassCastException if the instance is not `InvoicePaymentPlanNotFoundException`
     */
    public InvoicePaymentPlanNotFoundException getInvoicePaymentPlanNotFoundException() throws ClassCastException {
        return (InvoicePaymentPlanNotFoundException)super.getActualInstance();
    }
    /**
     * Get the actual instance of `InvalidInvoiceDueDateException`. If the actual instance is not `InvalidInvoiceDueDateException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `InvalidInvoiceDueDateException`
     * @throws ClassCastException if the instance is not `InvalidInvoiceDueDateException`
     */
    public InvalidInvoiceDueDateException getInvalidInvoiceDueDateException() throws ClassCastException {
        return (InvalidInvoiceDueDateException)super.getActualInstance();
    }
    /**
     * Get the actual instance of `IncorrectFinancingAmountException`. If the actual instance is not `IncorrectFinancingAmountException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `IncorrectFinancingAmountException`
     * @throws ClassCastException if the instance is not `IncorrectFinancingAmountException`
     */
    public IncorrectFinancingAmountException getIncorrectFinancingAmountException() throws ClassCastException {
        return (IncorrectFinancingAmountException)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to FinanceInvoice400Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with PlatformInvoiceIdAlreadyExistsException
        try {
            PlatformInvoiceIdAlreadyExistsException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for PlatformInvoiceIdAlreadyExistsException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with InvoicePaymentPlanNotFoundException
        try {
            InvoicePaymentPlanNotFoundException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for InvoicePaymentPlanNotFoundException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with InvalidInvoiceDueDateException
        try {
            InvalidInvoiceDueDateException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for InvalidInvoiceDueDateException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with IncorrectFinancingAmountException
        try {
            IncorrectFinancingAmountException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for IncorrectFinancingAmountException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for FinanceInvoice400Response with oneOf schemas: IncorrectFinancingAmountException, InvalidInvoiceDueDateException, InvoicePaymentPlanNotFoundException, PlatformInvoiceIdAlreadyExistsException. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of FinanceInvoice400Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of FinanceInvoice400Response
     * @throws IOException if the JSON string is invalid with respect to FinanceInvoice400Response
     */
    public static FinanceInvoice400Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, FinanceInvoice400Response.class);
    }

    /**
     * Convert an instance of FinanceInvoice400Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

