/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kanmon.client.model.DrawRequest;
import com.kanmon.client.model.PaginationResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.kanmon.client.JSON;

/**
 * GetDrawRequestsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-26T19:00:57.767815-07:00[America/Los_Angeles]", comments = "Generator version: 7.5.0")
public class GetDrawRequestsResponse {
  public static final String SERIALIZED_NAME_DRAW_REQUESTS = "drawRequests";
  @SerializedName(SERIALIZED_NAME_DRAW_REQUESTS)
  private List<DrawRequest> drawRequests = new ArrayList<>();

  public static final String SERIALIZED_NAME_PAGINATION = "pagination";
  @SerializedName(SERIALIZED_NAME_PAGINATION)
  private PaginationResult pagination;

  public GetDrawRequestsResponse() {
  }

  public GetDrawRequestsResponse drawRequests(List<DrawRequest> drawRequests) {
    this.drawRequests = drawRequests;
    return this;
  }

  public GetDrawRequestsResponse addDrawRequestsItem(DrawRequest drawRequestsItem) {
    if (this.drawRequests == null) {
      this.drawRequests = new ArrayList<>();
    }
    this.drawRequests.add(drawRequestsItem);
    return this;
  }

   /**
   * Array of draw requests.
   * @return drawRequests
  **/
  @javax.annotation.Nonnull
  public List<DrawRequest> getDrawRequests() {
    return drawRequests;
  }

  public void setDrawRequests(List<DrawRequest> drawRequests) {
    this.drawRequests = drawRequests;
  }


  public GetDrawRequestsResponse pagination(PaginationResult pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Pagination metadata.
   * @return pagination
  **/
  @javax.annotation.Nonnull
  public PaginationResult getPagination() {
    return pagination;
  }

  public void setPagination(PaginationResult pagination) {
    this.pagination = pagination;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDrawRequestsResponse getDrawRequestsResponse = (GetDrawRequestsResponse) o;
    return Objects.equals(this.drawRequests, getDrawRequestsResponse.drawRequests) &&
        Objects.equals(this.pagination, getDrawRequestsResponse.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(drawRequests, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDrawRequestsResponse {\n");
    sb.append("    drawRequests: ").append(toIndentedString(drawRequests)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("drawRequests");
    openapiFields.add("pagination");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("drawRequests");
    openapiRequiredFields.add("pagination");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetDrawRequestsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetDrawRequestsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetDrawRequestsResponse is not found in the empty JSON string", GetDrawRequestsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetDrawRequestsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetDrawRequestsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetDrawRequestsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("drawRequests").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `drawRequests` to be an array in the JSON string but got `%s`", jsonObj.get("drawRequests").toString()));
      }

      JsonArray jsonArraydrawRequests = jsonObj.getAsJsonArray("drawRequests");
      // validate the required field `drawRequests` (array)
      for (int i = 0; i < jsonArraydrawRequests.size(); i++) {
        DrawRequest.validateJsonElement(jsonArraydrawRequests.get(i));
      };
      // validate the required field `pagination`
      PaginationResult.validateJsonElement(jsonObj.get("pagination"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetDrawRequestsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetDrawRequestsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetDrawRequestsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetDrawRequestsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetDrawRequestsResponse>() {
           @Override
           public void write(JsonWriter out, GetDrawRequestsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetDrawRequestsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetDrawRequestsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetDrawRequestsResponse
  * @throws IOException if the JSON string is invalid with respect to GetDrawRequestsResponse
  */
  public static GetDrawRequestsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetDrawRequestsResponse.class);
  }

 /**
  * Convert an instance of GetDrawRequestsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

