/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms.  ## Rate limiting  Endpoints in this API enforce a per-platform request quota. Responses include the following headers when a quota is in effect:  - `X-RateLimit-Limit` — maximum requests allowed per minute. - `X-RateLimit-Remaining` — requests remaining in the current window.  When the quota is exhausted the API responds with `429 Too Many Requests`. Platforms without a configured quota are unlimited and these headers are omitted.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kanmon.client.model.InvoicePaymentPlanRepaymentWindow;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.kanmon.client.JSON;

/**
 * InvoicePaymentPlan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class InvoicePaymentPlan {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_ADVANCE_RATE_PERCENTAGE = "advanceRatePercentage";
  @SerializedName(SERIALIZED_NAME_ADVANCE_RATE_PERCENTAGE)
  private BigDecimal advanceRatePercentage;

  public static final String SERIALIZED_NAME_TRANSACTION_FEE_PERCENTAGE = "transactionFeePercentage";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_FEE_PERCENTAGE)
  private BigDecimal transactionFeePercentage;

  public static final String SERIALIZED_NAME_REPAYMENT_WINDOW = "repaymentWindow";
  @SerializedName(SERIALIZED_NAME_REPAYMENT_WINDOW)
  private InvoicePaymentPlanRepaymentWindow repaymentWindow;

  public InvoicePaymentPlan() {
  }

  public InvoicePaymentPlan id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The UUID representing the invoice payment plan.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public InvoicePaymentPlan advanceRatePercentage(BigDecimal advanceRatePercentage) {
    this.advanceRatePercentage = advanceRatePercentage;
    return this;
  }

  /**
   * The percentage of the invoice that is allowed for advances. E.g. a value of &#x60;80&#x60; would mean that $800 would be advanced on a $1,000 invoice.
   * @return advanceRatePercentage
   */
  @javax.annotation.Nonnull
  public BigDecimal getAdvanceRatePercentage() {
    return advanceRatePercentage;
  }

  public void setAdvanceRatePercentage(BigDecimal advanceRatePercentage) {
    this.advanceRatePercentage = advanceRatePercentage;
  }


  public InvoicePaymentPlan transactionFeePercentage(BigDecimal transactionFeePercentage) {
    this.transactionFeePercentage = transactionFeePercentage;
    return this;
  }

  /**
   * The percentage of the transaction that is charged as a fee. E.g. a value of &#x60;5&#x60; means 5%.
   * @return transactionFeePercentage
   */
  @javax.annotation.Nonnull
  public BigDecimal getTransactionFeePercentage() {
    return transactionFeePercentage;
  }

  public void setTransactionFeePercentage(BigDecimal transactionFeePercentage) {
    this.transactionFeePercentage = transactionFeePercentage;
  }


  public InvoicePaymentPlan repaymentWindow(InvoicePaymentPlanRepaymentWindow repaymentWindow) {
    this.repaymentWindow = repaymentWindow;
    return this;
  }

  /**
   * Get repaymentWindow
   * @return repaymentWindow
   */
  @javax.annotation.Nonnull
  public InvoicePaymentPlanRepaymentWindow getRepaymentWindow() {
    return repaymentWindow;
  }

  public void setRepaymentWindow(InvoicePaymentPlanRepaymentWindow repaymentWindow) {
    this.repaymentWindow = repaymentWindow;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InvoicePaymentPlan instance itself
   */
  public InvoicePaymentPlan putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePaymentPlan invoicePaymentPlan = (InvoicePaymentPlan) o;
    return Objects.equals(this.id, invoicePaymentPlan.id) &&
        Objects.equals(this.advanceRatePercentage, invoicePaymentPlan.advanceRatePercentage) &&
        Objects.equals(this.transactionFeePercentage, invoicePaymentPlan.transactionFeePercentage) &&
        Objects.equals(this.repaymentWindow, invoicePaymentPlan.repaymentWindow)&&
        Objects.equals(this.additionalProperties, invoicePaymentPlan.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, advanceRatePercentage, transactionFeePercentage, repaymentWindow, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePaymentPlan {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    advanceRatePercentage: ").append(toIndentedString(advanceRatePercentage)).append("\n");
    sb.append("    transactionFeePercentage: ").append(toIndentedString(transactionFeePercentage)).append("\n");
    sb.append("    repaymentWindow: ").append(toIndentedString(repaymentWindow)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("advanceRatePercentage");
    openapiFields.add("transactionFeePercentage");
    openapiFields.add("repaymentWindow");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("advanceRatePercentage");
    openapiRequiredFields.add("transactionFeePercentage");
    openapiRequiredFields.add("repaymentWindow");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InvoicePaymentPlan
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InvoicePaymentPlan.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InvoicePaymentPlan is not found in the empty JSON string", InvoicePaymentPlan.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InvoicePaymentPlan.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the required field `repaymentWindow`
      InvoicePaymentPlanRepaymentWindow.validateJsonElement(jsonObj.get("repaymentWindow"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InvoicePaymentPlan.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InvoicePaymentPlan' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InvoicePaymentPlan> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InvoicePaymentPlan.class));

       return (TypeAdapter<T>) new TypeAdapter<InvoicePaymentPlan>() {
           @Override
           public void write(JsonWriter out, InvoicePaymentPlan value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InvoicePaymentPlan read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             InvoicePaymentPlan instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InvoicePaymentPlan given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InvoicePaymentPlan
   * @throws IOException if the JSON string is invalid with respect to InvoicePaymentPlan
   */
  public static InvoicePaymentPlan fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InvoicePaymentPlan.class);
  }

  /**
   * Convert an instance of InvoicePaymentPlan to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

