/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The current status of the loan.&lt;table&gt;  &lt;tr&gt; &lt;td&gt;CURRENT&lt;/td&gt; &lt;td&gt;All scheduled loan payments are up to date&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;LATE&lt;/td&gt; &lt;td&gt;One or more scheduled loan payments are past due&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;FULLY_PAID&lt;/td&gt; &lt;td&gt;The loan has been fully repaid and closed. Not applicable for AR, AP, or Line of Credit products&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;REFINANCED&lt;/td&gt; &lt;td&gt;The loan has been refinanced and replaced by a new loan agreement. Not applicable for AR, AP, or Line of Credit products&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;CLOSED&lt;/td&gt; &lt;td&gt;The loan has been closed and is no longer active&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;DEFAULTED&lt;/td&gt; &lt;td&gt;The loan has been marked as defaulted due to missed payments&lt;/td&gt; &lt;/tr&gt; &lt;/table&gt;
 */
@JsonAdapter(LoanStatus.Adapter.class)
public enum LoanStatus {
  
  CURRENT("CURRENT"),
  
  LATE("LATE"),
  
  FULLY_PAID("FULLY_PAID"),
  
  REFINANCED("REFINANCED"),
  
  CLOSED("CLOSED"),
  
  DEFAULTED("DEFAULTED");

  private String value;

  LoanStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LoanStatus fromValue(String value) {
    for (LoanStatus b : LoanStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LoanStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final LoanStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LoanStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LoanStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    LoanStatus.fromValue(value);
  }
}

