/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PaymentIntentTriggerType
 */
@JsonAdapter(PaymentIntentTriggerType.Adapter.class)
public enum PaymentIntentTriggerType {
  
  DISBURSEMENT("DISBURSEMENT"),
  
  DISBURSEMENT_RETURN("DISBURSEMENT_RETURN"),
  
  SCHEDULED_REPAYMENT("SCHEDULED_REPAYMENT"),
  
  EARLY_PAYOFF("EARLY_PAYOFF"),
  
  REFINANCE_PAYOFF("REFINANCE_PAYOFF"),
  
  FEE("FEE"),
  
  REFUND("REFUND"),
  
  MINIMUM_PAYMENT("MINIMUM_PAYMENT");

  private String value;

  PaymentIntentTriggerType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentIntentTriggerType fromValue(String value) {
    for (PaymentIntentTriggerType b : PaymentIntentTriggerType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PaymentIntentTriggerType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentIntentTriggerType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentIntentTriggerType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentIntentTriggerType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PaymentIntentTriggerType.fromValue(value);
  }
}

