/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kanmon.client.model.PrimaryBusinessOwnerAlreadyExistsForBusinessException;
import com.kanmon.client.model.UserAlreadyExistsWithEmailException;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.kanmon.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-28T22:23:19.704752-07:00[America/Los_Angeles]", comments = "Generator version: 7.5.0")
public class UpdateUser409Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(UpdateUser409Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!UpdateUser409Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'UpdateUser409Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<UserAlreadyExistsWithEmailException> adapterUserAlreadyExistsWithEmailException = gson.getDelegateAdapter(this, TypeToken.get(UserAlreadyExistsWithEmailException.class));
            final TypeAdapter<PrimaryBusinessOwnerAlreadyExistsForBusinessException> adapterPrimaryBusinessOwnerAlreadyExistsForBusinessException = gson.getDelegateAdapter(this, TypeToken.get(PrimaryBusinessOwnerAlreadyExistsForBusinessException.class));

            return (TypeAdapter<T>) new TypeAdapter<UpdateUser409Response>() {
                @Override
                public void write(JsonWriter out, UpdateUser409Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `UserAlreadyExistsWithEmailException`
                    if (value.getActualInstance() instanceof UserAlreadyExistsWithEmailException) {
                        JsonElement element = adapterUserAlreadyExistsWithEmailException.toJsonTree((UserAlreadyExistsWithEmailException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `PrimaryBusinessOwnerAlreadyExistsForBusinessException`
                    if (value.getActualInstance() instanceof PrimaryBusinessOwnerAlreadyExistsForBusinessException) {
                        JsonElement element = adapterPrimaryBusinessOwnerAlreadyExistsForBusinessException.toJsonTree((PrimaryBusinessOwnerAlreadyExistsForBusinessException)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: PrimaryBusinessOwnerAlreadyExistsForBusinessException, UserAlreadyExistsWithEmailException");
                }

                @Override
                public UpdateUser409Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize UserAlreadyExistsWithEmailException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        UserAlreadyExistsWithEmailException.validateJsonElement(jsonElement);
                        actualAdapter = adapterUserAlreadyExistsWithEmailException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'UserAlreadyExistsWithEmailException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for UserAlreadyExistsWithEmailException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'UserAlreadyExistsWithEmailException'", e);
                    }
                    // deserialize PrimaryBusinessOwnerAlreadyExistsForBusinessException
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PrimaryBusinessOwnerAlreadyExistsForBusinessException.validateJsonElement(jsonElement);
                        actualAdapter = adapterPrimaryBusinessOwnerAlreadyExistsForBusinessException;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'PrimaryBusinessOwnerAlreadyExistsForBusinessException'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for PrimaryBusinessOwnerAlreadyExistsForBusinessException failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'PrimaryBusinessOwnerAlreadyExistsForBusinessException'", e);
                    }

                    if (match == 1) {
                        UpdateUser409Response ret = new UpdateUser409Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for UpdateUser409Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public UpdateUser409Response() {
        super("oneOf", Boolean.FALSE);
    }

    public UpdateUser409Response(PrimaryBusinessOwnerAlreadyExistsForBusinessException o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public UpdateUser409Response(UserAlreadyExistsWithEmailException o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("UserAlreadyExistsWithEmailException", UserAlreadyExistsWithEmailException.class);
        schemas.put("PrimaryBusinessOwnerAlreadyExistsForBusinessException", PrimaryBusinessOwnerAlreadyExistsForBusinessException.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return UpdateUser409Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PrimaryBusinessOwnerAlreadyExistsForBusinessException, UserAlreadyExistsWithEmailException
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof UserAlreadyExistsWithEmailException) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof PrimaryBusinessOwnerAlreadyExistsForBusinessException) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PrimaryBusinessOwnerAlreadyExistsForBusinessException, UserAlreadyExistsWithEmailException");
    }

    /**
     * Get the actual instance, which can be the following:
     * PrimaryBusinessOwnerAlreadyExistsForBusinessException, UserAlreadyExistsWithEmailException
     *
     * @return The actual instance (PrimaryBusinessOwnerAlreadyExistsForBusinessException, UserAlreadyExistsWithEmailException)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `UserAlreadyExistsWithEmailException`. If the actual instance is not `UserAlreadyExistsWithEmailException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `UserAlreadyExistsWithEmailException`
     * @throws ClassCastException if the instance is not `UserAlreadyExistsWithEmailException`
     */
    public UserAlreadyExistsWithEmailException getUserAlreadyExistsWithEmailException() throws ClassCastException {
        return (UserAlreadyExistsWithEmailException)super.getActualInstance();
    }
    /**
     * Get the actual instance of `PrimaryBusinessOwnerAlreadyExistsForBusinessException`. If the actual instance is not `PrimaryBusinessOwnerAlreadyExistsForBusinessException`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PrimaryBusinessOwnerAlreadyExistsForBusinessException`
     * @throws ClassCastException if the instance is not `PrimaryBusinessOwnerAlreadyExistsForBusinessException`
     */
    public PrimaryBusinessOwnerAlreadyExistsForBusinessException getPrimaryBusinessOwnerAlreadyExistsForBusinessException() throws ClassCastException {
        return (PrimaryBusinessOwnerAlreadyExistsForBusinessException)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to UpdateUser409Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with UserAlreadyExistsWithEmailException
        try {
            UserAlreadyExistsWithEmailException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for UserAlreadyExistsWithEmailException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with PrimaryBusinessOwnerAlreadyExistsForBusinessException
        try {
            PrimaryBusinessOwnerAlreadyExistsForBusinessException.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for PrimaryBusinessOwnerAlreadyExistsForBusinessException failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for UpdateUser409Response with oneOf schemas: PrimaryBusinessOwnerAlreadyExistsForBusinessException, UserAlreadyExistsWithEmailException. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of UpdateUser409Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of UpdateUser409Response
     * @throws IOException if the JSON string is invalid with respect to UpdateUser409Response
     */
    public static UpdateUser409Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, UpdateUser409Response.class);
    }

    /**
     * Convert an instance of UpdateUser409Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

