/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateBusinessBankAccountRequestBody {
    /**
    * Your platform’s unique business ID for the business. Either `platformBusinessId` or `businessId` is required.
    */
    'platformBusinessId'?: string;
    /**
    * The UUID representing the user’s business in Kanmon. Either `platformBusinessId` or `businessId` is required.
    */
    'businessId'?: string;
    /**
    * Your platform’s unique ID for the bank account.
    */
    'platformBankAccountId': string;
    /**
    * The business defined bank account name.
    */
    'accountName': string;
    /**
    * The business’s bank account number. Only digits, no formatting.
    */
    'accountNumber': string;
    /**
    * The business’s bank routing number. Should be a 9 digits number, no formatting.
    */
    'routingNumber': string;
    /**
    * The bank account’s type. Currently, we only support checking accounts. We may support others in the future.
    */
    'accountType': CreateBusinessBankAccountRequestBodyAccountTypeEnum;
    /**
    * The bank account’s roles. Currently, we only support creating disbursement bank account. We may support others in the future.
    */
    'roles': Array<CreateBusinessBankAccountRequestBodyRolesEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "platformBusinessId",
            "baseName": "platformBusinessId",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessId",
            "baseName": "businessId",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformBankAccountId",
            "baseName": "platformBankAccountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountName",
            "baseName": "accountName",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountNumber",
            "baseName": "accountNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "routingNumber",
            "baseName": "routingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountType",
            "baseName": "accountType",
            "type": "CreateBusinessBankAccountRequestBodyAccountTypeEnum",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<CreateBusinessBankAccountRequestBodyRolesEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateBusinessBankAccountRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CreateBusinessBankAccountRequestBodyAccountTypeEnum {
    Checking = 'CHECKING'
}
export enum CreateBusinessBankAccountRequestBodyRolesEnum {
    Disbursement = 'DISBURSEMENT'
}

