/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FixedDateInvoiceRepaymentWindow {
    'repaymentType': FixedDateInvoiceRepaymentWindowRepaymentTypeEnum;
    /**
    * The day on which the repayment is due. E.g. a value of `15` means the repayment is due on the 15th.
    */
    'monthlyRepaymentDay': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "repaymentType",
            "baseName": "repaymentType",
            "type": "FixedDateInvoiceRepaymentWindowRepaymentTypeEnum",
            "format": ""
        },
        {
            "name": "monthlyRepaymentDay",
            "baseName": "monthlyRepaymentDay",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FixedDateInvoiceRepaymentWindow.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum FixedDateInvoiceRepaymentWindowRepaymentTypeEnum {
    FixedDate = 'FIXED_DATE'
}

