/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SessionInvoiceWithInvoiceFile } from '../models/SessionInvoiceWithInvoiceFile';
import { HttpFile } from '../http/http';

export class InvoiceFlowWithInvoiceFileSessionTokenData {
    'component': InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum;
    /**
    * Details about the list of invoices which are to be created.
    */
    'invoices': Array<SessionInvoiceWithInvoiceFile>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "component",
            "baseName": "component",
            "type": "InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum",
            "format": ""
        },
        {
            "name": "invoices",
            "baseName": "invoices",
            "type": "Array<SessionInvoiceWithInvoiceFile>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvoiceFlowWithInvoiceFileSessionTokenData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum InvoiceFlowWithInvoiceFileSessionTokenDataComponentEnum {
    SessionInvoiceFlowWithInvoiceFile = 'SESSION_INVOICE_FLOW_WITH_INVOICE_FILE'
}

