/**
 * Kanmon Public V2 API
 * Kanmon\'s public api. Contains all of the endpoints for both capital providers and platforms
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MergeUsersRequestBody {
    /**
    * Your platform’s unique business ID for the business to merge users from. Either `sourcePlatformBusinessId` or `sourceBusinessId` is required.
    */
    'sourcePlatformBusinessId'?: string;
    /**
    * The UUID representing the business in Kanmon to merge users from. Either `sourcePlatformBusinessId` or `sourceBusinessId` is required.
    */
    'sourceBusinessId'?: string;
    /**
    * Your platform’s unique business ID for the business to merge users to. Either `targetPlatformBusinessId` or `targetBusinessId` is required.
    */
    'targetPlatformBusinessId'?: string;
    /**
    * The UUID representing the business in Kanmon to merge users to. Either `targetPlatformBusinessId` or `targetBusinessId` is required.
    */
    'targetBusinessId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sourcePlatformBusinessId",
            "baseName": "sourcePlatformBusinessId",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceBusinessId",
            "baseName": "sourceBusinessId",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetPlatformBusinessId",
            "baseName": "targetPlatformBusinessId",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetBusinessId",
            "baseName": "targetBusinessId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MergeUsersRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

