name: TS Release

on:
  pull_request:
    branches:
      - main
    paths:
      - "kanmon_api_spec.json"
      - "openapitools.json"
      - "ts/**"
      - ".github/workflows/ts-release.yml"
    # tags:
    #   - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/@kanmon"

      - name: Generate openapi lib
        run: |
          yarn
          yarn openapi-generator-cli generate

      - name: Install modules
        run: |
          cd ts
          yarn

      # git config user.name "$ {{ github.event.pusher.name }}"
      # git config user.email "$ {{ github.event.pusher.email }}"
      - name: Publish (pre-release)
        if: github.ref_type == 'branch'
        run: |
          git config user.name "coleby"
          git config user.email "25941617+coleby@users.noreply.github.com"
          cd ts
          yarn version --prerelease --preid next-${{ github.sha }}
          yarn publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: github.ref_type == 'tag'
        run: |
          cd ts
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
