name: TS Release

on:
  push:
    branches:
      - main
    paths:
      - "kanmon_api_spec.json"
      - "openapitools.json"
      - "ts/**"
      - ".github/workflows/ts-release.yml"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # 4.3.0
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      # Temporarily disabled until a new version is pushed including:
      # https://github.com/OpenAPITools/openapi-generator/pull/18877/files
      # - name: Generate openapi lib
      #   run: |
      #     yarn
      #     yarn openapi-generator-cli generate

      - name: Install modules
        run: |
          cd ts
          yarn

      - name: Publish (pre-release)
        if: github.ref_type == 'branch'
        run: |
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          cd ts
          yarn version --prerelease --preid next-${{ github.sha }}
          yarn publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: github.ref_type == 'tag'
        run: |
          cd ts
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
