/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateIntegratedMcaReceivableBody
 */
public class CreateIntegratedMcaReceivableBodyTest {
    private final CreateIntegratedMcaReceivableBody model = new CreateIntegratedMcaReceivableBody();

    /**
     * Model tests for CreateIntegratedMcaReceivableBody
     */
    @Test
    public void testCreateIntegratedMcaReceivableBody() {
        // TODO: test CreateIntegratedMcaReceivableBody
    }

    /**
     * Test the property 'issuedProductId'
     */
    @Test
    public void issuedProductIdTest() {
        // TODO: test issuedProductId
    }

    /**
     * Test the property 'chargeAmountCents'
     */
    @Test
    public void chargeAmountCentsTest() {
        // TODO: test chargeAmountCents
    }

    /**
     * Test the property 'repaymentAmountCents'
     */
    @Test
    public void repaymentAmountCentsTest() {
        // TODO: test repaymentAmountCents
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'transactionTime'
     */
    @Test
    public void transactionTimeTest() {
        // TODO: test transactionTime
    }

}
