/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kanmon.client.model.ActivityLog;
import com.kanmon.client.model.PaginationResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetActivityLogsResponse
 */
public class GetActivityLogsResponseTest {
    private final GetActivityLogsResponse model = new GetActivityLogsResponse();

    /**
     * Model tests for GetActivityLogsResponse
     */
    @Test
    public void testGetActivityLogsResponse() {
        // TODO: test GetActivityLogsResponse
    }

    /**
     * Test the property 'activityLogs'
     */
    @Test
    public void activityLogsTest() {
        // TODO: test activityLogs
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    public void paginationTest() {
        // TODO: test pagination
    }

}
