/*
 * Kanmon Public V2 API
 * Kanmon's public api. Contains all of the endpoints for both capital providers and platforms
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kanmon.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoicePaymentPlan
 */
public class InvoicePaymentPlanTest {
    private final InvoicePaymentPlan model = new InvoicePaymentPlan();

    /**
     * Model tests for InvoicePaymentPlan
     */
    @Test
    public void testInvoicePaymentPlan() {
        // TODO: test InvoicePaymentPlan
    }

    /**
     * Test the property 'advanceRatePercentage'
     */
    @Test
    public void advanceRatePercentageTest() {
        // TODO: test advanceRatePercentage
    }

    /**
     * Test the property 'transactionFeePercentage'
     */
    @Test
    public void transactionFeePercentageTest() {
        // TODO: test transactionFeePercentage
    }

    /**
     * Test the property 'repaymentWindow'
     */
    @Test
    public void repaymentWindowTest() {
        // TODO: test repaymentWindow
    }

}
